import type { Metadata } from 'next'
import '../globals.css'
import Navbar from '../components/Navbar'
import { montserrat } from '../utils/fonts'
import Footer from '@/components/Footer'
import SearchServer from '@/components/Search/Search'
import Filters from '@/components/Filters'
import dynamic from 'next/dynamic'

const CartProvider = dynamic(() => import('./cart/components/CartProvider'), { ssr: false })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default async function RootLayout ({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={montserrat.className + ' antialiased'}>
        <Navbar Mobile={<Filters />} Desktop={<SearchServer />} />
          <CartProvider>
            {children}
          </CartProvider>
        <Footer />
      </body>
    </html>
  )
}
