import type { Metadata } from 'next'
import '../globals.css'
import Navbar from '../components/Navbar'
import { montserrat } from '../utils/fonts'
import Footer from '@/components/Footer'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default async function RootLayout ({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={montserrat.className + ' antialiased'}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  )
}
